import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Header.module.css'
import Switcher from '../DarkMode/Switcher'

function Header({ title }: { title?: string }) {
  const { data: session } = useSession()
  return (
    <div>
      <Head>
        <title>{`Blog ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.Header}>
        <div className={styles.Div}>
          <Link href="/">
            <a className={styles.A}>
              <span className={`${styles.Span} dark:text-white`}>Blog</span>
            </a>
          </Link>

          <nav className={styles.Nav}>
            <Link href="/">
              <a className={`${styles.PagesLink} dark:text-gray-200`}>
                Featured Posts
              </a>
            </Link>
            <Link href="/">
              <a className={`${styles.PagesLink} dark:text-gray-200`}>
                Categories
              </a>
            </Link>
            <Link href="/">
              <a className={`${styles.PagesLink} dark:text-gray-200`}>
                About Us
              </a>
            </Link>
            <Switcher />
          </nav>

          <div className={styles.Buttons}>
            {session ? (
              <button
                onClick={() => signOut({ callbackUrl: '/' })}
                className={styles.SignIn}
              >
                Sign Out
              </button>
            ) : (
              <button
                onClick={() => signIn('google', { callbackUrl: '/' })}
                className={styles.SignIn}
              >
                Sign In
              </button>
            )}
          </div>
        </div>
      </header>
    </div>
  )
}

export default Header
