import { MenuIcon, XIcon } from '@heroicons/react/solid'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React, { Fragment } from 'react'
import Switcher from '../../DarkMode/Switcher'
import { IoArrowBack } from 'react-icons/io5'
import { signIn, useSession } from 'next-auth/react'
import Sidebar from './Sidebar'
import MenuComponent from './Menu'
import { Links } from './Links'

function Header({ title }: { title?: string }) {
  const router = useRouter()
  const homepage = router.pathname === '/'
  const { data: session } = useSession()
  const data = Links
  return (
    <div>
      <Head>
        <title>{`Blog ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-between border-b border-gray-300 px-4 py-4 dark:border-gray-500 md:flex-row-reverse md:px-10">
        <div className="flex items-center space-x-4">
          <div className="hidden space-x-4 md:flex">
            {data.map((item) => (
              <Link key={item.id} href={item.link}>
                <a className="hover:text-indigo-300">{item.name}</a>
              </Link>
            ))}
          </div>

          {homepage ? (
            <Switcher />
          ) : (
            <button
              className="rounded-lg bg-gray-100 p-1 hover:bg-gray-200 dark:bg-gray-700 hover:dark:bg-gray-600 md:hidden"
              onClick={() => router.back()}
            >
              <IoArrowBack className="h-5 w-5 text-gray-800 dark:text-gray-200" />
            </button>
          )}
          <div className="hidden md:flex">
            {session ? (
              <MenuComponent />
            ) : (
              <button
                onClick={() => signIn('google')}
                className="rounded-md bg-lime-500 py-2 px-4 font-medium text-gray-800 hover:bg-lime-500/90"
              >
                Sign In
              </button>
            )}
          </div>
        </div>
        <Link href="/">
          <a className="group text-lg font-medium italic text-gray-400 dark:text-gray-200 dark:hover:text-gray-300">
            Gaming{' '}
            <span className="text-red-500 dark:group-hover:text-red-400">
              Duniya
            </span>
          </a>
        </Link>

        <Sidebar />
      </div>
    </div>
  )
}

export default Header
